INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Books', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Science Fiction', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Dystopian novels', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Action & Adventure', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Mystery', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Horror', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Thriller & Suspense', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Historical fiction', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Romance', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Woman fiction', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('LGBTQ+', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Contemporany fiction', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Literary fiction', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Magical realism', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Graphic novel', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Short story', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Young adult', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('New adult', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Childrens', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Memoir & AutoBiiography', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Biography', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Food & drink', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Art & Photography', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Books', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('History', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Travel', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('True crime', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Humor', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Essay', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Guide / How-to', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Religion & Spirituality', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Science & Technology', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Eletronics', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Computers', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Souces', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Pasta', NOW());
INSERT INTO tb_category (NAME, CREATED_AT) VALUES ('Food', NOW());
